web_codebase/django-codebase/BBS/BBS_main/BBS_main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app01 import views
from django.views.static import serve
from BBS_main import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('app01/', include("app01.urls"), name="app01"),

    # 登录注销
    path('login/', views.login, name="login"),
    path("logout/", views.logout, name="logout"),

    # 注册
    path("register/", views.register, name="register"),
    # 首页
    path("home/", views.home, name="home"),
    # 开设后端接口
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

web_codebase/django-codebase/BBS/BBS_main/app01/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app01 import views

urlpatterns = [
    path("set_password/", views.ser_password, name="ser_password"),

    # 图片验证码相关
    path("get_code/", views.get_code, name="get_code"),

    # 文章评论
    path("article_comment/", views.article_comment, name="article_comment"),
    # 文章修改
    path("backend/", views.backend, name="backend"),
    path("backend/add/article", views.backend_add_article, name="backend_add_article"),

    # 编辑器上传图片
    path("backend/upload_img", views.upload_img, name="upload_img"),

    # 修改用户头像
    path("set/avatar", views.set_avatar, name="set_avatar"),

    # 个人站点
    path("<str:username>/", views.site, name="site"),
    # 侧边栏筛选
    # re_path("(?P<username>\w+)/category/(\d+)/", views.site),
    # re_path("(?P<username>\w+)/tag/(\d+)/", views.site),
    # re_path("(?P<username>\w+)/archive/(\w+)/", views.site),
    # 合并上面三条url
    re_path("^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)/", views.site),

    path("<str:username>/article/<int:article_id>", views.article_detail, name="article_detail"),

    # 点赞点擦
    path("up_or_down/", views.up_or_down, name="up_or_down"),


]

web_codebase/django-codebase/BBS/BBS_main/app01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
"""
先写普通字段
再写外键字段
"""


class UserInfo(AbstractUser):
    phone = models.BigIntegerField(verbose_name="手机号", null=True, blank=True)
    """
    null=True 数据库可以为空
    blank=True 后台管理可以为空
    """

    # 头像
    avatar = models.FileField(upload_to="avatar/", default="avatar/default.png", verbose_name="用户头像")
    # 设置文件保存地址，如果没有就设置默认头像

    create_time = models.DateField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = "用户表"


class Blog(models.Model):
    site_name = models.CharField(verbose_name="站点名称", max_length=32)
    site_title = models.CharField(verbose_name="站点标题", max_length=32)
    site_theme = models.CharField(verbose_name="站点样式", max_length=64)  # 存储css、js路径

    def __str__(self):
        return self.site_name


class Category(models.Model):
    name = models.CharField(verbose_name="文章分类", max_length=32)

    blog = models.ForeignKey(to="Blog", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(verbose_name="文章标签", max_length=32)

    blog = models.ForeignKey(to="Blog", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(verbose_name="文章标题", max_length=64)
    desc = models.CharField(verbose_name="文章简介", max_length=255)
    # 文章内容有很多，一般情况下都是使用TextFiled()
    content = models.TextField(verbose_name="文章内容")

    create_time = models.DateField(auto_now_add=True)

    up_num = models.BigIntegerField(default=0, verbose_name="点赞数")
    down_num = models.BigIntegerField(default=0, verbose_name="点踩数")
    comment_num = models.BigIntegerField(default=0, verbose_name="评论数")

    # 外键
    blog = models.ForeignKey(to="Blog", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(to="Category", on_delete=models.CASCADE, null=True)

    tags = models.ManyToManyField(
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag")
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    article = models.ForeignKey(to="Article", on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.article}:{self.tag}"

class UpAndDown(models.Model):
    user = models.ForeignKey(to="UserInfo", on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey(to="Article", on_delete=models.SET_NULL, null=True)
    is_up = models.BooleanField()


class Comment(models.Model):
    user = models.ForeignKey(to="UserInfo", on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey(to="Article", on_delete=models.SET_NULL, null=True)
    content = models.CharField(max_length=32, verbose_name="评论内容")
    comment_time = models.DateTimeField(auto_now_add=True)
    # 自关联
    parent = models.ForeignKey(to="self", on_delete=models.CASCADE,null=True)

web_codebase/django-codebase/BBS/BBS_main/app01/views.py
import json
import time
import os.path
import random
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse, HttpResponse
from app01.app01_forms import MyRegForm
from app01 import models
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO, StringIO
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.db.models import F
from django.db import transaction
from utils.app01_page import Pagination
from bs4 import BeautifulSoup
from BBS_main import settings


# Create your views here.
# 注册
def register(requests):
    """
    注册模块
    :param requests:
    :return:
    """
    form_obj = MyRegForm()
    if requests.method == "POST":
        back_dict = {"code": 200, "msg": ""}

        # 校验数据是否合法
        form_obj = MyRegForm(requests.POST)
        if form_obj.is_valid():

            # 将数据另存
            cleaned_data = form_obj.cleaned_data
            # 将两次密码删除一个
            cleaned_data.pop("confirm_password")
            # 获取文件对象
            file_obj = requests.FILES.get("avatar")
            # 判断是否有值
            if file_obj:
                cleaned_data["avatar"] = file_obj
            # 操作数据库保存
            models.UserInfo.objects.create_user(**cleaned_data)
            back_dict["url"] = redirect("login").url

        else:

            back_dict["code"] = 2000
            back_dict["msg"] = form_obj.errors

        return JsonResponse(back_dict)
    return render(requests, "app01/register.html", locals())


# 登录
def login(requests):
    """
    登录验证模块
    :param requests:
    :return:
    """
    if requests.method == "POST":
        back_dic = {"code": 200, "msg": ""}
        username = requests.POST.get("username")
        password = requests.POST.get("password")
        id_code = requests.POST.get("id_code")
        if requests.session.get("code").upper() == id_code.upper():
            # 校验账号密码是否正确
            user_obj = auth.authenticate(requests, username=username, password=password)
            if user_obj:
                # 保存用户状态
                auth.login(requests, user_obj)
                back_dic["url"] = reverse("home")
            else:
                back_dic["code"] = 402
                back_dic["msg"] = "用户名或者密码错误"
        else:
            back_dic["code"] = 403
            back_dic["msg"] = "验证码错误"
        return JsonResponse(back_dic)
    return render(requests, "app01/login.html")


# 修改密码
@login_required
def ser_password(requests):
    if requests.is_ajax():
        back_dict = {"code": 200, "msg": ""}
        if requests.method == "POST":
            old_password = requests.POST.get("old_password")
            new_password = requests.POST.get("new_password")
            confirm_password = requests.POST.get("confirm_password")
            is_right = requests.user.check_password(old_password)
            print(is_right, old_password)
            if is_right:
                if new_password == confirm_password:
                    requests.user.set_password(new_password)
                    requests.user.save()
                    back_dict["msg"] = "ok"
                else:
                    back_dict["code"] = 1001
                    back_dict["msg"] = "两次密码不正确"
            else:
                back_dict["code"] = 1002
                back_dict["msg"] = "与原密码不正确"
        return JsonResponse(back_dict)
    return HttpResponse("ser_password")


# 退出登录
def logout(requests):
    auth.logout(requests)
    return redirect("login")


# 生成RGB颜色
def get_random_rgb():
    """
    生成一个随机的RGB颜色
    :return:
    """
    return random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)


# 获取验证码
def get_code(requests):
    """
    随机验证码
    :param requests:
    :return:
    """
    # 利用pillow模块产生图片
    img_obj = Image.new("RGB", (480, 35), get_random_rgb())
    img_draw = ImageDraw.Draw(img_obj)
    img_font = ImageFont.truetype("static/app01/fonts/雷鬼One.ttf", 30)  # 样式和大小

    code = ""
    for i in range(6):
        # 大写字母
        random_upper = chr(random.randint(65, 90))
        # 小写字母
        random_lower = chr(random.randint(97, 122))
        # 数字
        random_num = str(random.randint(0, 9))
        # 从三个中随机选择一个
        tmp = random.choice([random_num, random_lower, random_upper])
        # 将产生的随机字符串写入图片
        # 一个个写可以控制间隙，一次性写无法控制
        img_draw.text((i * 50, 0), tmp, get_random_rgb(), img_font)  # 位置，文字，颜色，字体样式
        code += tmp
    # 随机字符串要在登录的时候使用到，要对比，所以要找一个地方存下来
    print(code)
    requests.session["code"] = code
    io_obj = BytesIO()
    img_obj.save(io_obj, "png")
    return HttpResponse(io_obj.getvalue())


# 主页
def home(requests):
    # 查询本网站下所有文章数据，
    article_queryset = models.Article.objects.all()

    # 分页
    page_obj = Pagination(
        current_page=requests.GET.get("page", 1),
        all_count=article_queryset.count(),
        per_page_num=10,
    )
    page_queryset = article_queryset[page_obj.start:page_obj.end]

    return render(requests, "app01/home.html", locals())


# 个人站点
def site(requests, username, **kwargs):
    """

    :param requests:
    :param username:
    :param kwargs: 如果改参数有就是要做额为的筛选
    :return:
    """
    # 先校验当前用户名对应的个人站点是否存在
    user_obj = models.UserInfo.objects.filter(username=username).first()
    # 若不存在404
    if not user_obj:
        return render(requests, "error_404.html")
    blog = user_obj.blog
    # 查询个人站点下的所有文章
    article_list = models.Article.objects.filter(blog=blog)
    # 判断是否有参数
    if kwargs:
        condition = kwargs.get("condition")
        param = kwargs.get("param")
        # 判断用户筛选的条件
        if condition == "category":
            # 查分类
            article_list = article_list.filter(category_id=param)
        elif condition == "tag":
            # 查出标签id 多对多
            article_list = article_list.filter(tags__id=param)
        elif condition == "archive":
            year, month = param.split("-")
            # 查时间
            article_list = article_list.filter(create_time__year=year, create_time__month=month)
        else:
            return render(requests, "error_404.html")

    # # 1.查询当前用户所有的分类及分类小的文章数
    # category_list = models.Category.objects.filter(blog=blog).annotate(
    #     count_name=Count("article__pk")
    # ).values("pk", "name", "count_name")
    #
    # # 2.差早当前用户所有的标签和标签数
    # tag_list = models.Tag.objects.filter(blog=blog).annotate(
    #     count_name=Count("article__pk")
    # ).values("pk", "name", "count_name")
    #
    # # 3.更加年月份分组统计
    # data_list = models.Article.objects.filter(blog=blog).annotate(
    #     month=TruncMonth("create_time")).values("month").annotate(
    #     count_name=Count("pk")).values("month", "count_name")

    # 分页
    page_obj = Pagination(
        current_page=requests.GET.get("page", 1),
        all_count=article_list.count(),
        per_page_num=10,
    )
    page_queryset = article_list[page_obj.start:page_obj.end]

    return render(requests, "app01/site.html", locals())


# 文章详情
def article_detail(requests, username, article_id):
    """
    应该校验username和article_id是否存在，
    :param requests:
    :param username:用户名
    :param article_id:文章id
    :return:
    """

    article_obj = models.Article.objects.filter(pk=article_id, blog__userinfo__username=username).first()
    if not article_obj:
        return render(requests, "error_404.html")

    user_obj = models.UserInfo.objects.filter(username=username).first()
    blog = user_obj.blog

    # 获取当前文章的所有评论内容

    comment_list = models.Comment.objects.filter(article=article_obj)

    return render(requests, "app01/article_detail.html", locals())

    pass


# 点赞和点踩
def up_or_down(requests):
    """
    1.校验登录
    2. 自己不能给自己点
    3。只能点一次
    4.操作数据库
    点赞点擦的处理
    :param requests:
    :return:
    """
    if requests.is_ajax():
        back_dict = {"code": 200, "msg": ""}

        # 判断是否登录
        if requests.user.is_authenticated:
            article_id = requests.POST.get("article_id")
            is_up = json.loads(requests.POST.get("is_up"))

            # 判断是否是自己写的
            article_obj = models.Article.objects.filter(pk=article_id).first()
            if not article_obj.blog.userinfo == requests.user:

                # 校验用户是否已经点过
                is_click = models.UpAndDown.objects.filter(user=requests.user, article=article_obj)
                if not is_click:

                    # 操作数据库 ,要同步操作
                    # 判断是点赞还是点擦
                    if is_up:
                        # 给点赞增加一
                        models.Article.objects.filter(pk=article_id).update(up_num=F("up_num") + 1)
                        back_dict["msg"] = "点赞成功"
                        pass
                    else:
                        # 给点擦加一
                        models.Article.objects.filter(pk=article_id).update(down_num=F("down_num") + 1)
                        back_dict["msg"] = "点踩成功"
                    # 操作表
                    models.UpAndDown.objects.create(user=requests.user, article=article_obj, is_up=is_up)
                else:
                    # 校验用户是否已经点过
                    back_dict["code"] = 2001
                    back_dict["msg"] = "你已经点过l"
            else:
                # 判断是否是自己写的
                back_dict["code"] = 2002
                back_dict["msg"] = "不可以点自己"
        else:
            # 判断是否登录
            back_dict["code"] = 2003
            back_dict["msg"] = '<a href="/login/">要登录哦</a>'
        return JsonResponse(back_dict)


# 文章评论
def article_comment(requests):
    """
    自己可以给自己评论
    :param requests:
    :return:
    """
    back_dict = {"code": 200, "msg": ""}
    if requests.is_ajax():
        if requests.method == "POST":
            if requests.user.is_authenticated:
                article_id = requests.POST.get("article_id")
                parentId = requests.POST.get("parentId")
                comment = requests.POST.get("comment")

web_codebase/django-codebase/BBS/BBS_main/templates/app01/app10_backend/backend.html
{% extends "app01/app10_backend/backend_base.html" %}


{% block article %}
    <table class="table table-hover">
        <thead>
        <tr>
            <td>标题</td>
            <td>评论数</td>
            <td>点赞数</td>
            <td>操作</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        {% for article in page_queryset %}
            <tr>
                <td><a href="{% url 'article_detail' article.blog.userinfo.username article.pk %}">{{ article.title }}</a></td>
                <td>{{ article.comment_num }}</td>
                <td>{{ article.up_num }}</td>
                <td><a href="#">编辑</a></td>
                <td><a href="#">删除</a></td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <div class="pull-right">
        {{ page_obj.page_html|safe }}

    </div>
{% endblock %}

web_codebase/django-codebase/BBS/BBS_main/templates/app01/app10_backend/backend_add_article.html
{% extends  "app01/app10_backend/backend_base.html" %}
{% load static %}


{% block article %}
    <h3>添加文章</h3>
    {#    直接利用form表单#}
    <form action="" method="post">
        {% csrf_token %}
        <p>标题</p>
        <div>
            <input type="text" name="title" class="form-control">
        </div>
        <p>内容</p>
        <div>
            <textarea name="content" id="id_content" cols="30" rows="10"></textarea>
        </div>

        <p>分类</p>
        <div>
            {% for category in category_list %}
                <input type="radio" value="{{ category.pk }}" name="category">{{ category.name }}

            {% endfor %}

        </div>
        <p>标签</p>
        <div>
            {% for tag in tag_list %}
                <input type="checkbox" value="{{ tag.pk }}" name="tag">{{ tag.name }}

            {% endfor %}

        </div>
        <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}


{% block js %}
    <script charset="utf-8" src="{% static 'app01/kindeditor/kindeditor-all-min.js' %}"></script>
    <script charset="utf-8" src="{% static 'app01/kindeditor/lang/zh-CN.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content',
                {
                    width: '100%',
                    height: "400px",
                    resizeType: 1,
                    uploadJson: '{% url 'upload_img' %}', //上传图片后端的位置
                    extraFileUploadParams: {
                        //支持上传文件携带参数
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    }
                }
            );
        });
    </script>
{% endblock %}

web_codebase/django-codebase/BBS/BBS_main/templates/app01/app10_backend/backend_base.html
{% load static %}
{% load temp_1 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'app01/js/jquery-3.6.0.js' %}"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="{% static 'app01/css/bootstrap.min.css' %}">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="{% static 'app01/js/bootstrap.min.js' %}"></script>

    {% block css %}

    {% endblock %}


    {% if requests.user.blog.site_theme and requests.user.blog.site_theme != "null" %}
        <link rel="stylesheet" href="/media/css/{{ requests.user.blog.site_theme }}">
    {% endif %}


<body>

<div class="top_navigation">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">{{ blog.site_title }}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'site' requests.user.username %}">{{ requests.user.blog.site_title }}</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home' %}">博客 <span class="sr-only">(current)</span></a></li>
                    <li><a href="{% url 'site'  requests.user.username %}">文章</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">更多 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if requests.user.is_authenticated %}
                        <li><a href="#">{{ requests.user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">更多操作<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">修改密码</a></li>
                                <li><a href="{% url 'set_avatar' %}">修改头像</a></li>
                                <li><a href="{% url 'backend' %}">后台管理</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'logout' %}">退出登录</a></li>
                            </ul>
                            <!-- 修改密码 -->
                            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
                                 aria-labelledby="myLargeModalLabel">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <h1 class="text-center">修改密码</h1>
                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-2">
                                                <div class="form-group">
                                                    <label for="">用户名</label>
                                                    <input type="text" disabled value="{{ requests.user.username }}"
                                                           class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">原密码</label>
                                                    <input type="password" id="id_old_password" name="old_password"
                                                           class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">新密码</label>
                                                    <input type="password" id="id_new_password" class="form-control"
                                                           name="new_password">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">确认新密码</label>
                                                    <input type="password" id="id_confirm_password"
                                                           class="form-control"
                                                           name="confirm_password">
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                                        取消
                                                    </button>
                                                    <button type="button" class="btn btn-primary" id="id_edit">确认
                                                    </button>
                                                </div>
                                                <span style="color: red" id="span_error"></span>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                    {% else %}
                        <li><a href="{% url 'register' %}">注册</a></li>
                        <li><a href="{% url 'login' %}">登录</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            {#            {% left_menu requests.user.username %}#}
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                               aria-expanded="true" aria-controls="collapseOne">
                                更多操作
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="{% url 'backend_add_article' %}">添加文章</a>
                        </div>
                        <div class="panel-body">
                            <a href="#">添加随笔</a>
                        </div>
                        <div class="panel-body">
                            <a href="#">草稿箱</a>
                        </div>
                        <div class="panel-body">
                            <a href="#">其他</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#article" aria-controls="article" role="tab" data-toggle="tab">文章</a>
                    </li>
                    <li role="presentation">
                        <a href="#informalEssay" aria-controls="informalEssay" role="tab" data-toggle="tab">随笔</a>
                    </li>
                    <li role="presentation">
                        <a href="#draft" aria-controls="draft" role="tab" data-toggle="tab">草稿</a>
                    </li>
                    <li role="presentation">
                        <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">设置</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="article">
                        {% block article %}

                        {% endblock %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="informalEssay">
                        {% block informalEssay %}

                        {% endblock %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="draft">
                        {% block draft %}

                        {% endblock %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="settings">
                        {% block settings %}

                        {% endblock %}
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

{% block js %}

{% endblock %}
</body>
</html>

web_codebase/django-codebase/BBS/BBS_main/templates/app01/app10_backend/set_avatar.html
{% extends "base.html" %}

{% block content %}
    <h3 class="text-center">修改头像</h3>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            原头像:
            <img src="/media/{{ requests.user.avatar }}" alt="{{ requests.user.username }}">
        </p>
        <p>

        <div class="form-group">
            <label for="myfile">新头像
                <img src="/media/avatar/default.png" id="myfileImg" alt="" width="80px"
                     style="margin-left: 10px">
            </label>
            <input type="file" id="myfile" style="display: none" name="avatar">
        </div>
        </p>
        <input type="submit" class="btn btn-default" value="提交">
    </form>



{% endblock %}


{% block js %}
    <script>
        {#实时显示头像#}
        $("#myfile").change(function () {
            {#文件阅读器对象#}
            {#1.生成一个文件阅读器对象#}
            let myFileReaderObj = new FileReader()
            {#2.获取用户上传的头像文件对象#}
            let fileObj = $(this)[0].files[0]
            {#3.将文件对象交给阅读器对象读取#}
            myFileReaderObj.readAsDataURL(fileObj)  //异步操作

            {#4.利用文件阅读器将文件展示到前端  修改src属性#}
            // 文件阅读器加载完毕再执行
            myFileReaderObj.onload = function () {
                $("#myfileImg").attr("src", myFileReaderObj.result)
            }

        })


    </script>

{% endblock %}